### ISSUE TITLE
推荐支持批量模式

### ISSUE THREAD

**Issue by shiny** [HaveTwoBrush/img2img#1]
例如：`jpg2png ./*.jpg` 或者 `jpg2png .` 生成到当前目录
原因：找个命令一键处理，省的写脚本，否则这个命令和 mac 自带的 sips 没多少区别了

**Comment by Ailln** [comment]
好的，我会在近期加入这个功能。

**Comment by shiny** [comment]
酷，感谢🙏

**Comment by Ailln** [comment]
`v0.2.0` 已经增加批量转化。使用方式如下：

```bash
jpg2png ./test/
```
